project:
  type: website
engine: knitr
website:
  title: "Mae Saslaw"
  navbar:
    background: primary
    foreground: light 
    left:
      - href: index.qmd
        text: Home
      - cv.qmd
      - projects.qmd
    collapse: true
  page-footer:
    background: primary
    foreground: light
    right:
      - text: GitHub
        href: https://github.com/saslaw
      - text: ORCID
        href: https://orcid.org/0000-0003-0169-6487
      - text: Google Scholar
        href: https://scholar.google.com/citations?user=hgpd7fMAAAAJ&hl=en
  search: false

format:
  html:
    theme: 
      - litera
      - styles.scss
    link-external-newwindow: true
    toc: false


