project:
  type: website
engine: knitr
format:
  html:
    theme: 
      - litera
      - styles.scss
    link-external-newwindow: true
    toc: false
website:
  title: "Mae Saslaw"
  favicon: images/hammer.png
  navbar:
    background: primary
    foreground: light 
    left:
      - href: index.qmd
        text: Home
      - cv.qmd
      - projects.qmd
    right:
      - text: GitHub
        href: https://github.com/saslaw
      - text: ORCID
        href: https://orcid.org/0000-0003-0169-6487
      - text: Google Scholar
        href: https://scholar.google.com/citations?user=hgpd7fMAAAAJ&hl=en
    collapse: true
  page-footer:
    background: primary
    foreground: light
    right:
      - text: Made with Quarto
        href: https://quarto.org
  search: false
  announcement: 
    icon: easel
    dismissable: false
    content: "I'm going to AGU24! Stop by [my presentations](agu24.qmd) and follow [#AGU24 on Bluesky](https://bsky.app/hashtag/AGU24)"
    type: info
    position: below-navbar